<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Discover all modules and generate bootstrap cache files.
 *
 * Scans module.json files in app-modules/ and vendor/ directories,
 * validates manifests, checks dependencies, and writes modules.php
 * with parsed manifest metadata. Composer remains responsible for
 * autoloading modules through path or VCS repositories.
 */
class ModuleCacheCommand extends Command
{
    protected $signature = 'module:cache
        {--force : Re-cache even if cache file exists}';

    protected $description = 'Discover all modules and generate bootstrap cache files';

    private const MODULES_CACHE = 'bootstrap/cache/modules.php';

    /**
     * Execute the console command.
     *
     * Scans module.json files in app-modules/ and vendor/ directories,
     * validates manifests, checks dependencies, and writes modules.php.
     */
    public function handle(): int
    {
        $this->components->info('Discovering module manifests...');

        $modules = $this->discoverModules();

        $this->components->twoColumnDetail('Modules found', (string) count($modules));

        foreach ($modules as $name => $manifest) {
            $this->components->twoColumnDetail("  {$name}", $manifest['version']);
        }

        $this->writeModulesCache($modules);
        $this->components->info('Module cache generated successfully.');

        return self::SUCCESS;
    }

    /**
     * Discover all modules from the filesystem.
     */
    private function discoverModules(): array
    {
        $modules = [];

        foreach (glob(base_path('app-modules/*/module.json')) as $path) {
            $manifest = $this->loadManifest($path);

            if ($manifest !== null) {
                $modules[$manifest['name']] = $manifest;
            }
        }

        foreach (glob(base_path('vendor/*/*/module.json')) as $path) {
            $manifest = $this->loadManifest($path);

            if ($manifest !== null) {
                $modules[$manifest['name']] = $manifest;
            }
        }

        uasort($modules, fn (array $a, array $b): int => ($a['priority'] ?? 0) <=> ($b['priority'] ?? 0));

        return $modules;
    }

    /**
     * Load and validate a single module.json file.
     */
    private function loadManifest(string $path): ?array
    {
        $content = file_get_contents($path);

        if ($content === false) {
            return null;
        }

        $manifest = json_decode($content, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            $this->components->warn("Invalid JSON in [{$path}].");

            return null;
        }

        $required = ['name', 'version', 'namespace', 'display_name'];

        foreach ($required as $field) {
            if (! isset($manifest[$field]) || (is_string($manifest[$field]) && trim($manifest[$field]) === '')) {
                $this->components->warn("Manifest [{$path}] missing required field: [{$field}].");

                return null;
            }
        }

        if (! preg_match('/^[a-z][a-z0-9_-]*$/', $manifest['name'])) {
            $this->components->warn("Manifest [{$path}] has invalid module name.");

            return null;
        }

        return $manifest;
    }

    /**
     * Write the modules.php cache file containing all module manifests.
     */
    private function writeModulesCache(array $modules): void
    {
        $path = base_path(self::MODULES_CACHE);

        $content = "<?php\n\n/*\n|--------------------------------------------------------------------------\n| Module Manifests\n|--------------------------------------------------------------------------\n|\n| This file is automatically generated by 'php artisan module:cache'.\n| It contains the parsed manifests of all discovered modules.\n|\n*/\n\nreturn ".var_export($modules, true).";\n";

        file_put_contents($path, $content, LOCK_EX);
    }
}
