#!/bin/bash
# ==============================================================================
# TallPBX Host Security & Firewall (nftables)
# ==============================================================================
# This installer step configures host-level Linux kernel packet filtering using
# modern nftables, installs the dedicated bounded host security helper, and
# establishes baseline firewall rules for VoIP, SIP, RTP, Web admin, and SSH.
#
# What this step changes:
# 1. Installs the 'nftables' package via Debian/Ubuntu apt package manager.
# 2. Creates the shared configuration directory '/etc/tallpbx' with secure setgid
#    permissions (mode 2775, owned by root:www-data) so the web application can
#    safely stage validated firewall configuration files.
# 3. Installs the bounded host helper '/usr/local/sbin/tallpbx-security' with
#    restricted permissions (mode 0750, owned by root:www-data) to perform
#    kernel-level nftables operations without granting general root access.
# 4. Installs the sudoers drop-in '/etc/sudoers.d/tallpbx-security' (mode 0440,
#    owned by root:root) allowing 'www-data' to invoke only that specific helper.
# 5. Seeds the standard PBX Port Catalog and security configuration settings in
#    the database if the Laravel application is present.
# 6. Enables and starts the 'nftables' systemd service and generates an initial
#    safe baseline ruleset ensuring SSH, Web, SIP, and RTP traffic remain open.
#
# Safe to re-run:
# - All package, file, and directory operations are idempotent.
# - Existing custom firewall rules in the database are preserved.
# - If the nftables service is already running, re-running simply re-checks rules.
# ==============================================================================

# Stop execution if any command fails unexpectedly
set -e

# Change directory to the script's folder so relative paths resolve reliably
cd "$(dirname "$0")"

# Load installer helper functions, color codes, and environment defaults
. ./config.sh
. ./colors.sh
. ./environment.sh

# ------------------------------------------------------------------------------
# 1. Install nftables packet filtering package
# ------------------------------------------------------------------------------
# Nftables is the modern Linux kernel packet classification and firewall framework,
# replacing legacy iptables. It provides zero-daemon automatic kernel timeouts for
# IP banning and atomic ruleset replacement.
verbose "Installing nftables package"
apt_get_with_lock_wait install -y nftables

# ------------------------------------------------------------------------------
# 2. Setup configuration directory for firewall rulesets
# ------------------------------------------------------------------------------
# The '/etc/tallpbx' directory holds both the live active firewall ruleset
# (firewall.nft) and the pending ruleset (firewall.nft.pending) generated by the
# web UI.
#
# We set mode 2775 with group ownership 'www-data' and the setgid bit enabled.
# This allows PHP-FPM web workers to write pending ruleset files, while all newly
# created files automatically inherit the www-data group.
verbose "Configuring firewall configuration directory in /etc/tallpbx"
install -d -m 2775 -o root -g www-data /etc/tallpbx

# ------------------------------------------------------------------------------
# 3. Install bounded host security helper
# ------------------------------------------------------------------------------
# To prevent arbitrary remote code execution or root privilege escalation,
# the web interface is strictly forbidden from running arbitrary system commands.
# All privileged kernel firewall operations are encapsulated in a single,
# root-owned script that validates all inputs against strict regular expressions.
verbose "Installing bounded host security helper to /usr/local/sbin/tallpbx-security"
install -m 0750 -o root -g www-data ./tallpbx-security /usr/local/sbin/tallpbx-security

# ------------------------------------------------------------------------------
# 4. Install bounded sudoers configuration
# ------------------------------------------------------------------------------
# This sudoers file grants 'www-data' passwordless sudo access strictly and only
# to '/usr/local/sbin/tallpbx-security'. No wildcards or shell escapes are permitted.
verbose "Installing sudoers rule for security helper"
install -m 0440 -o root -g root ./tallpbx-security.sudoers /etc/sudoers.d/tallpbx-security

# Verify sudoers syntax before proceeding to prevent administrative lockout
if ! visudo -c -f /etc/sudoers.d/tallpbx-security >/dev/null 2>&1; then
    error "Sudoers syntax verification failed for /etc/sudoers.d/tallpbx-security"
    rm -f /etc/sudoers.d/tallpbx-security
    exit 1
fi

# ------------------------------------------------------------------------------
# 5. Seed PBX Port Catalog and compile baseline firewall rules
# ------------------------------------------------------------------------------
# If the TallPBX Laravel application is deployed, seed the database with the
# standard PBX services (SIP, RTP, Web Admin, SSH, ESL, WebSockets, WebRTC)
# and generate the initial baseline ruleset in /etc/tallpbx/firewall.nft.
if [ -f /var/www/tallpbx/artisan ]; then
    verbose "Seeding standard PBX services and security defaults"
    (cd /var/www/tallpbx && php artisan db:seed --class=Database\\Seeders\\SecurityServiceSeeder --force)

    verbose "Generating and applying initial baseline firewall ruleset"
    # Attempt to apply the ruleset via the security CLI command. In virtualized
    # or containerized environments where the Linux kernel lacks NET_ADMIN
    # privileges, do not halt the entire installer if packet filter application
    # is restricted by the container host.
    if ! (cd /var/www/tallpbx && php artisan security:apply --force); then
        warning "Could not apply nftables kernel ruleset directly (kernel packet filtering may be restricted in this environment)."
    fi
fi

# ------------------------------------------------------------------------------
# 6. Configure boot persistence and start nftables service
# ------------------------------------------------------------------------------
# On Debian/Ubuntu systems, systemd's 'nftables.service' loads /etc/nftables.conf
# upon server boot. By default, /etc/nftables.conf contains an empty skeleton
# that discards custom firewall tables upon reboot.
#
# We configure /etc/nftables.conf to include the active TallPBX configuration
# (/etc/tallpbx/firewall.nft). This guarantees that all firewall rules, port
# allowances, IP whitelists, and active dynamic attacker bans persist across
# server restarts without administrative intervention.
if [ -f /etc/tallpbx/firewall.nft ]; then
    verbose "Configuring boot persistence in /etc/nftables.conf"
    cat << 'EOF' > /etc/nftables.conf
#!/usr/sbin/nft -f

# TallPBX Host Firewall Configuration
# This file is loaded automatically by systemd nftables.service upon server boot.
# It includes the compiled active firewall ruleset generated by the web panel.
include "/etc/tallpbx/firewall.nft"
EOF
    chmod 0644 /etc/nftables.conf
fi

verbose "Enabling and starting nftables systemd service"
systemctl daemon-reload 2>/dev/null || true
systemctl enable nftables 2>/dev/null || true
systemctl restart nftables 2>/dev/null || true
