<?php

declare(strict_types=1);

namespace Modules\Transcribe\Models;

use App\Traits\BelongsToTenant;
use Database\Factories\Pbx\TranscriptionFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Stores speech-to-text transcription results for voicemail messages.
 *
 * Each transcription is linked to a voicemail message and contains
 * the transcribed text, a confidence score, and the detected language.
 * Transcriptions are generated by an external STT engine and stored
 * here for admin review and search.
 *
 * @property string $id UUID primary key
 * @property int $tenant_id
 * @property string $voicemail_message_id FK to the original voicemail recording
 * @property string $text The transcribed text content
 * @property float|null $confidence STT confidence score (0.00-0.99)
 * @property string|null $language Detected language code (e.g. en-US)
 */
class Transcription extends Model
{
    use BelongsToTenant;
    use HasFactory;
    use HasUuids;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'tenant_id', 'voicemail_message_id', 'text', 'confidence', 'language',
    ];

    /**
     * The attributes that should be cast to native types.
     */
    protected function casts(): array
    {
        return ['confidence' => 'decimal:2'];
    }

    /**
     * Create a new factory instance for this model.
     */
    protected static function newFactory(): TranscriptionFactory
    {
        return TranscriptionFactory::new();
    }
}
