<?php

declare(strict_types=1);

namespace App\Support;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RuntimeException;
use SplFileInfo;
use Symfony\Component\Process\Process;

/**
 * Repairs TallPBX file ownership and modes for generated, runtime, or full application scopes.
 */
class ApplicationFilePermissions
{
    /**
     * Create a repair service for the deployed application or an isolated test directory.
     */
    public function __construct(private readonly ?string $rootPath = null) {}

    /**
     * Apply the ownership and mode policy for the requested scope.
     */
    public function repair(PermissionRepairScope $scope): void
    {
        if ($scope === PermissionRepairScope::Generated) {
            $this->repairGeneratedPaths();

            return;
        }

        if ($scope === PermissionRepairScope::Runtime) {
            $this->repairRuntimePaths();

            return;
        }

        $this->ensureFullRepairCanRun();
        $this->repairFullApplication();
    }

    /**
     * Repair only files generated by Artisan and Vite.
     */
    private function repairGeneratedPaths(): void
    {
        foreach ([
            $this->path('bootstrap/cache'),
            $this->path('storage/framework/views'),
            $this->path('public/build'),
        ] as $path) {
            $this->repairRuntimeTree($path);
        }
    }

    /**
     * Repair all Laravel writable directories and their generated files.
     */
    private function repairRuntimePaths(): void
    {
        foreach ([$this->path('storage'), $this->path('bootstrap/cache')] as $path) {
            $this->repairRuntimeTree($path);
        }

        $this->repairGeneratedPaths();
    }

    /**
     * Repair deployed source, Composer packages, secrets, and Laravel runtime files.
     */
    private function repairFullApplication(): void
    {
        foreach ([
            'app', 'app-modules', 'bootstrap', 'config', 'database', 'docs', 'lang', 'public', 'resources', 'routes', 'scripts', 'tests',
        ] as $path) {
            $this->repairSourceTree($this->path($path));
        }

        $this->repairVendorTree($this->path('vendor'));
        $this->repairSourceFiles();
        $this->repairEnvironmentFile();
        $this->repairRuntimePaths();
        $this->repairGitRepository();
        $this->restoreTrackedExecutableModes();
    }

    /**
     * Repair a deployed source tree without allowing PHP-FPM to write it.
     */
    private function repairSourceTree(string $path): void
    {
        $this->repairTree($path, 'root', 'www-data', 0755, 0644);
    }

    /**
     * Repair Composer packages while keeping existing package commands executable
     * and allowing the web user (www-data) to install/update packages.
     */
    private function repairVendorTree(string $path): void
    {
        $this->repairTree($path, 'root', 'www-data', 02775, 0664, true);
    }

    /**
     * Repair a Laravel runtime directory with group inheritance for new files.
     */
    private function repairRuntimeTree(string $path): void
    {
        $this->repairTree($path, 'www-data', 'www-data', 02775, 0664);
    }

    /**
     * Repair one tree and its descendants without following symbolic links.
     */
    private function repairTree(string $path, string $owner, string $group, int $directoryMode, int $fileMode, bool $preserveExecutables = false): void
    {
        if (! file_exists($path)) {
            return;
        }

        $this->repairFileInfo(new SplFileInfo($path), $owner, $group, $directoryMode, $fileMode, $preserveExecutables);

        if (! is_dir($path)) {
            return;
        }

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST,
        );

        foreach ($files as $file) {
            $this->repairFileInfo($file, $owner, $group, $directoryMode, $fileMode, $preserveExecutables);
        }
    }

    /**
     * Apply ownership and a safe mode to one file-system item.
     */
    private function repairFileInfo(SplFileInfo $file, string $owner, string $group, int $directoryMode, int $fileMode, bool $preserveExecutables): void
    {
        if ($file->isLink()) {
            return;
        }

        $path = $file->getPathname();
        $isExecutable = $preserveExecutables && $file->isFile() && is_executable($path);

        @chown($path, $owner);
        @chgrp($path, $group);
        @chmod($path, $file->isDir() ? $directoryMode : ($isExecutable ? 0755 : $fileMode));
    }

    /**
     * Repair source files that live in the application root.
     */
    private function repairSourceFiles(): void
    {
        foreach (['artisan', 'composer.json', 'package.json', 'vite.config.js'] as $path) {
            $this->repairTree($this->path($path), 'root', 'www-data', 0755, 0644);
        }

        foreach (['composer.lock', 'package-lock.json'] as $path) {
            $this->repairTree($this->path($path), 'root', 'www-data', 0755, 0664);
        }
    }

    /**
     * Protect the environment file because it contains application secrets.
     */
    private function repairEnvironmentFile(): void
    {
        $path = $this->path('.env');

        if (! file_exists($path)) {
            return;
        }

        @chown($path, 'root');
        @chgrp($path, 'www-data');
        @chmod($path, 0640);
    }

    /**
     * Restore executable modes tracked by Git after broad mode normalization.
     */
    private function restoreTrackedExecutableModes(): void
    {
        $process = new Process(['git', '-C', $this->root(), 'ls-files', '-s']);
        $process->run();

        if (! $process->isSuccessful()) {
            return;
        }

        foreach (explode("\n", trim($process->getOutput())) as $line) {
            if (! str_starts_with($line, '100755 ')) {
                continue;
            }

            $parts = explode("\t", $line, 2);

            if (count($parts) === 2 && file_exists($this->path($parts[1]))) {
                @chmod($this->path($parts[1]), 0755);
            }
        }
    }

    /**
     * Repair Git repository access so both administrators and the web user can perform safe Git operations.
     */
    private function repairGitRepository(): void
    {
        $gitDir = $this->path('.git');

        // Only repair Git repository files if this deployment is a Git worktree.
        if (! is_dir($gitDir)) {
            return;
        }

        // Apply group-shareable modes: directories are 2775 (setgid www-data) and files are 664.
        // This ensures the www-data group can read and write repository metadata alongside root.
        $this->repairTree($gitDir, 'root', 'www-data', 02775, 0664);

        // Instruct Git to create new repository objects with group permissions.
        $sharedConfig = new Process(['git', '-C', $this->root(), 'config', 'core.sharedRepository', 'group']);
        $sharedConfig->run();

        // Trust the deployed application path system-wide so both root and www-data can run Git.
        // This is only executed on the actual deployed application root when running as root.
        if ($this->rootPath === null && function_exists('posix_geteuid') && posix_geteuid() === 0) {
            $checkProcess = new Process(['git', 'config', '--system', '--get-all', 'safe.directory']);
            $checkProcess->run();

            if (! str_contains($checkProcess->getOutput(), $this->root())) {
                $safeDirProcess = new Process(['git', 'config', '--system', '--add', 'safe.directory', $this->root()]);
                $safeDirProcess->run();
            }
        }

        // Ensure web user SSH keys/config (for private Git repos) are secure and accessible
        $sshDir = '/var/www/.ssh';
        if (is_dir($sshDir)) {
            @chown($sshDir, 'www-data');
            @chgrp($sshDir, 'www-data');
            @chmod($sshDir, 0700);

            foreach (['id_rsa', 'id_ed25519', 'config'] as $file) {
                if (file_exists($sshDir.'/'.$file)) {
                    @chown($sshDir.'/'.$file, 'www-data');
                    @chgrp($sshDir.'/'.$file, 'www-data');
                    @chmod($sshDir.'/'.$file, 0600);
                }
            }

            if (file_exists($sshDir.'/known_hosts')) {
                @chown($sshDir.'/known_hosts', 'www-data');
                @chgrp($sshDir.'/known_hosts', 'www-data');
                @chmod($sshDir.'/known_hosts', 0644);
            }
        }

        // Ensure web user cache directory (for Composer package cache) is accessible
        $cacheDir = '/var/www/.cache';
        if (is_dir($cacheDir)) {
            $this->repairTree($cacheDir, 'www-data', 'www-data', 02775, 0664);
        }
    }

    /**
     * Refuse a full repair unless the process can safely change source ownership.
     */
    private function ensureFullRepairCanRun(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() !== 0) {
            throw new RuntimeException('A full permission repair must run as root.');
        }
    }

    /**
     * Build an absolute path within the application root.
     */
    private function path(string $path): string
    {
        return $this->root().'/'.$path;
    }

    /**
     * Return the configured test root or Laravel's deployed application root.
     */
    private function root(): string
    {
        return $this->rootPath ?? base_path();
    }
}
